name: My first git hub action project
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  Hello World:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: runing an Hello World
        run: echo " Hello World"
        shell: bash
 
  Closing Greatings:
    runs-on: ubuntu-latest
    steps:
      - name: Closing the Hello World Greeting
        run: echo " i am closing the Hello World welcome message"
        shell: bash
  
