name: comment on an issue
on:
  issues:
    types: [opened]
jobs:
  comment_issues:
    runs-on: ubuntu-latest
    steps:
      - name: dump-context
        run: echo '${{toJSON(github.event)}}'| jq
        shell: bash
        

  create-api-comment-issue:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: new-test-w
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |  
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Uzomaemekakingsley/my-git-hub-action-practice/issues/${ISSUE_NUMBER}/comments \
            -f body='Me too' 
      
          
          
          
          
          
      
