name: comment on an issue
on:
  issues:
    types: [opened]
jobs:
  comment_issues:
    runs-on: ubuntu-latest
    steps:
      - name: dump-context
        run: echo '${{toJSON(github.event)}}'| jq
        shell: bash
        

  create-api-comment-issue:
    runs-on: ubuntu-latest
    steps:
      - name: api-commet-issue
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${ORGANISATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='Me too' 
        env:
          GITHUB_TOKEN: ${{ secretes.GITHUB_TOKEN }}
          ORGANISATION: ${{ github.event.organisation.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          
      
